### ISSUE TITLE
Skip 'splitting the reference genome sequence' stage if it has already been split

### ISSUE THREAD

**Issue by kim-fehl** [paulstothard/cgview_comparison_tool#2]
Seems that this stage could be skipped if already done during previous runs, especially considering that it is using only one CPU and is somewhat slow.

`Splitting the reference genome sequence in NZ_CP009909/cct_projects/dna_vs_dna/reference_genome for BLAST searches.`

**Comment by kim-fehl** [comment]
After downloading gb file manually from ncbi long preprocessing issue disappeared.

**Comment by BachBioinformatics** [comment]
Trying to do `redraw_maps.sh -p myproject -f svg` or `build_blast_atlas.sh -p project -m 48g` but i am getting the same following error :

_```
org.xml.sax.SAXException: value for 'start' attribute in featureRange element must be less than or equal to the length of the plasmid in null at line 52 column 48
        at ca.ualberta.stothard.cgview.CgviewFactory.handleFeatureRange(CgviewFactory.java:3570)
        at ca.ualberta.stothard.cgview.CgviewFactory.startElement(CgviewFactory.java:669)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:497)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:180)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:275)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1654)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:324)
        at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:845)
        at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:768)
        at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1201)
        at ca.ualberta.stothard.cgview.CgviewFactory.createCgviewFromFile(CgviewFactory.java:445)
        at ca.ualberta.stothard.cgview.CgviewIO.main(CgviewIO.java:1474)
The following error occurred: org.xml.sax.SAXException: value for 'start' attribute in featureRange element must be less than or equal to the length of the plasmid in null at line 52 column 48
```_

Any tips?

Many thanks
